name: Docker Image CI

on:
  push:
    branches: [ "main" ]
# on:
#   push:
#     tags:
#     - '*.*.*'
jobs:
  # build_and_pub:
  #   runs-on: [ubuntu-latest]
  #   env:
  #     LOGIN: ${{ secrets.DOCKER_LOGIN }}
  #     NAME: ${{ secrets.DOCKER_NAME }}
  #   steps:
  #     - name: Login to docker
  #       run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
  #     - uses: actions/checkout@master
  #     - name: Build image
  #       run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
  #     - name: Push image to docker
  #       run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: '${{ secrets.DOCKER_LOGIN }}/${{ secrets.DOCKER_NAME }}:${GITHUB_REF:10}'
